#pragma config(Motor,  port2,           motorShoulder, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           motorArm,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           clawServo,     tmotorServoStandard, openLoop)
#pragma config(Motor,  port5,           motorBase,     tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
  //test
	while (0!=1)
	{
		startMotor(motorShoulder,63);
		wait(.5);
		stopMotor(motorShoulder);

	}


}
